#! /bin/dash

sxhkd &
#xrdb .Xresources

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width 1
bspc config window_gap 16

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle  false
bspc config automatic_scheme     longest_side

bspc config focused_border_color "#23FFD4"
bspc config normal_border_color "#3C454D"

. $HOME/.config/bspwm/rules
# bspc config external_rules_command .config/bspwm/external_rules

xsetroot -cursor_name left_ptr &
$HOME/.autoexec &
